### ISSUE TITLE
フレンドがプレイ中のステータス表示が正しくない

### ISSUE THREAD

**Issue by yuutenn** [NPJigaK/deadlock-japanese#46]
- 日本語化ファイルの対応バージョン
    - Build 5.260 2024/10/11 - 20:20:48

- 発生している現象
  - フレンドがオンラインかつプレイ中の時に表示されるステータスが「{%param1%} でプレイ中 %param0% 分経過」という表記になっている(下記画像参照)
![image](https://github.com/user-attachments/assets/6b32d881-0b2a-499e-8670-0ab229da2fc1)

**Comment by NPJigaK** [comment]
@yuutenn 
https://x.com/steinsgg/status/1845067729826668670

こちら確認したところDeadlock側の仕様（バグ）でした。
英語版でも同じく表示がおかしくなっていました。

**Comment by yuutenn** [comment]
@NPJigaK 
回答ありがとうございます。
Deadlock側の対応を待ちます。
